### ISSUE TITLE
Please make the text "More Info" editable for the user

### ISSUE THREAD

**Issue by ClaudiaLev** [Kipjr/cookieconsent#1]
It would be good when the user can not only change the URL but can change the words "More Info" to the language of the website.

**Comment by Kipjr** [comment]
This should have been fixed by 9ef3189891431baaae2cf645f7f5686bae703d92 , could you confirm this?

**Comment by ClaudiaLev** [comment]
Yes, it is fixed with the new version of the plugin.
Thanks!
