### ISSUE TITLE
Mobile Device

### ISSUE THREAD

**Issue by Ainz** [Kipjr/cookieconsent#13]
Normally I would not care about smartphones and such, but ...

I am not sure if I configured right, but on mobile device I am unable to hit the "Accept" button unless I scroll way to the right, I guess it does not adapt to the narrower view...

Example from https://www.homeworldshots.net/ 

Please test to verify.

**Comment by Kipjr** [comment]
Yes, I have the same issue when I visit your site.

**Comment by Kipjr** [comment]
I will try to fix it . Will probably be the end of the week

**Comment by Kipjr** [comment]
@Ainz , this should be fixed now:
https://github.com/Kipjr/cookieconsent/releases/tag/12.0.0c

**Comment by Ainz** [comment]
Indeed it is. Thank you very much.
