### ISSUE TITLE
Collides with plugin "Contact Form"

### ISSUE THREAD

**Issue by Kettenknecht** [Kipjr/cookieconsent#2]
If i use cookiconsent, the contact form from contactform plugin dissapears. Tried this with various themes, also cleared colpiled theme cache. If you nee further information, pleas feel free to ask.

**Comment by Kipjr** [comment]
At which place does the contactform inject Into the piwigo core code?

**Comment by Kipjr** [comment]
please compare both main.inc.php files, perhaps there are vars or functions with the same name.

**Comment by Kipjr** [comment]
I installed ContactForm and I notice no issues. I deactivated CookieConsent and activated it again (to simulate reinstall after contactform) and still I dont see anything. Could you open the WebDev tools (F12) when you experience this and copy the data from the console tab?

**Comment by Kettenknecht** [comment]
Sorry for late reaction:

Uncaught Error: LiveValidation::initialize - No element with reference or id of 'subject' exists!
    at LiveValidation.initialize (1cbp8qf.js:7)
    at new LiveValidation (1cbp8qf.js:7)
    at index.php?/contact/:186
    at index.php?/contact/:197
DevTools failed to parse SourceMap: https://smofoto.de/_data/combined/popper.min.js.map;
DevTools failed to parse SourceMap: https://smofoto.de/_data/combined/bootstrap.min.css.map

**Comment by Kipjr** [comment]
the livevalidation script isn't being loaded correctly. I'm unable to reproduce it but I will look into it. You have piwigo at newest version? Only difference with mine is is that I have it on my subdomain https://mydomain.home/piwigo

**Comment by Kipjr** [comment]
I checked it with https://piwigo.mydomain.home and got no issues here..

**Comment by Kipjr** [comment]
Could you disable Cookieconsent and open the page and right mouse button - view source
Then enable Cookieconsent and open the page and right mouse button - view source

Compare both sources and post the differences if you can.
