### ISSUE TITLE
authorize user Piwigo-TranslationTeam

### ISSUE THREAD

**Issue by ddtddt** [Kipjr/cookieconsent#3]
Hi :-)

For add your project on https://piwigo.org/translate, can you give acces to user Piwigo-TranslationTeam and say me it's ok ;-)

**Comment by ddtddt** [comment]
Hi :-)
Do you sent invitation to specified user ?

**Comment by Kipjr** [comment]
How and where should this be performed?

**Comment by ddtddt** [comment]
Hi :-)

in settings / Manage access
invite a collaborator
Piwigo-TranslationTeam

Thanks

**Comment by Kipjr** [comment]
done

**Comment by Piwigo-TranslationTeam** [comment]
Are you sure it was done? I can't push on your repository :-/

**Comment by Kipjr** [comment]
Still on pending invitation

**Comment by Piwigo-TranslationTeam** [comment]
My bad, I didn't see the invitation in my inbox and I didn't validate it quickly enough. Now it's expired. Can you resend it to me?

**Comment by Kipjr** [comment]
@Piwigo-TranslationTeam . Done.
