### ISSUE TITLE
minor issue with html formatting

### ISSUE THREAD

**Issue by Ainz** [Kipjr/cookieconsent#5]
THANK you for the html formatting. Excellent and superfast. :) 

two details... illustrated by my screenshot
- there is a trailing dot in the button text form
- the button text do not take the same formatting as the message text which I illustrated by exaggerating the size using H3

![image](https://user-images.githubusercontent.com/3930716/94360993-7f4e9580-00b1-11eb-9301-ea9959a3d1cb.png)

**Comment by Kipjr** [comment]
fixed with 96417bf
Thanks for the feedback
