### ISSUE TITLE
Update to version 11?

### ISSUE THREAD

**Issue by PhotoKevin** [Kipjr/cookieconsent#9]
This looks like something I really should be using. Any chance of updating it to install in the latest version of Piwigo?

Thanks,
Kevin

**Comment by Kipjr** [comment]
I will work on it!

**Comment by PhotoKevin** [comment]
Thanks, I think it's just a "supported version" comment change.

**Comment by Kipjr** [comment]
@PhotoKevin , Version 12 has been released. [V12.0.0a](https://github.com/Kipjr/cookieconsent/releases/tag/12.0.0a)
